# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4.3
      with:
        java-version: '8'          # Changed from 1.8 to 8
        distribution: 'temurin'    # ADDED: Required distribution parameter
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    # Optional: List built artifacts for debugging
    - name: List build artifacts
      run: |
        echo "Contents of build/libs/:"
        ls -la build/libs/ || echo "build/libs/ directory not found"
    
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: minjun6251/test-project
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
